version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - localnetwork

  mariadb:
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - localnetwork
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    links:
      - mariadb
    depends_on:
      mariadb:
        condition: service_started
        restart: true
      mongodb:
        condition: service_started
    restart: on-failure
    environment:
      APPLICATION_TRANSPORT_HTTP_PORT: 3000
      APPLICATION_GRACEFUL_MAX_SECOND: 20s
      AUTH_JWT_TOKEN_PUBLIC_KEY: |
        -----BEGIN PUBLIC KEY-----
        MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAw/oZbh6vDshOD7cqfUsj
        hXitgaiasXhUHF+EryNKVEVss38x9u6qYEyyYjo76bOVUrzMCsVvBkCR1E+Ga7XW
        5TICSS8yv3krvkYI0nrr0Fl7oqmiE/GpFbSw5WqqCjqo9PhRpfc/Y5wMGffJ1g7N
        2i1YpbR3KXC7klbdEx+oJR6hS/+b3Jq9oq0SBh9RO06pSmm5CX9vQrhPBwKbkSUN
        SzFxZcVl5uMRX0lrmycT2i2JZjywhpAPVr+/fRw8hoWffAjW8QSRQvEe6pGA8oas
        DEfuSN+YEmYudIWod5pVARXOdjC/VJWHrAuurtShhKu/fwsJFkt8bV9aEKEsLij2
        pbe8BS5twW6aDToo29XrDJqAQScROdRY9Cvsr0gBn8Xi5ueQTdEVAl5iYJRE84Tl
        Zww7OGaznjH/5NVj9MWQEG+uRMwjlp3P5igTHd2kdLd2OFECzaQWCZfd4Gb+AwUN
        zFUXuxnfm4ZTVmuRrCwq/bLoW8ief7uf6G1326sqHnGGbf9HasbVs7jiJIuMQaar
        601wewwFOTofsGbshbxuvubvrAp/jz5GDAsoArQBEoj0in46kT9W7KYoMmfmSj3E
        kP+LDqjd5qTDdQgban69nSHL1CiKFhxFrL2fz/Aw5VFW7r2RNFU8DjehECv0PclO
        HBMBFuAhVonYno5+wf75fIcCAwEAAQ==
        -----END PUBLIC KEY-----
      AUTH_JWT_TOKEN_PRIVATE_KEY: |
        -----BEGIN RSA PRIVATE KEY-----
        MIIJKQIBAAKCAgEAw/oZbh6vDshOD7cqfUsjhXitgaiasXhUHF+EryNKVEVss38x
        9u6qYEyyYjo76bOVUrzMCsVvBkCR1E+Ga7XW5TICSS8yv3krvkYI0nrr0Fl7oqmi
        E/GpFbSw5WqqCjqo9PhRpfc/Y5wMGffJ1g7N2i1YpbR3KXC7klbdEx+oJR6hS/+b
        3Jq9oq0SBh9RO06pSmm5CX9vQrhPBwKbkSUNSzFxZcVl5uMRX0lrmycT2i2JZjyw
        hpAPVr+/fRw8hoWffAjW8QSRQvEe6pGA8oasDEfuSN+YEmYudIWod5pVARXOdjC/
        VJWHrAuurtShhKu/fwsJFkt8bV9aEKEsLij2pbe8BS5twW6aDToo29XrDJqAQScR
        OdRY9Cvsr0gBn8Xi5ueQTdEVAl5iYJRE84TlZww7OGaznjH/5NVj9MWQEG+uRMwj
        lp3P5igTHd2kdLd2OFECzaQWCZfd4Gb+AwUNzFUXuxnfm4ZTVmuRrCwq/bLoW8ie
        f7uf6G1326sqHnGGbf9HasbVs7jiJIuMQaar601wewwFOTofsGbshbxuvubvrAp/
        jz5GDAsoArQBEoj0in46kT9W7KYoMmfmSj3EkP+LDqjd5qTDdQgban69nSHL1CiK
        FhxFrL2fz/Aw5VFW7r2RNFU8DjehECv0PclOHBMBFuAhVonYno5+wf75fIcCAwEA
        AQKCAgAf93GidrrTTHT/Nz9lBJactNyIY7on7Jq7rhD0iGsdZ92dQcgioTeFUb1f
        LGSNcE+RGV6m+yFrAalH2ljwxM5ywD+DNIGwndE2zjGuM4K3j4ENPWJEooyUD88y
        /L0TwhHBM6gNzFC4rMGEktiHZA7L4c2t6cvuJIdUDXsuHWHN/DsPLHh9+XepS1W/
        TehwJhqTGr+l/vVlCq9JU3GQsVyDwWLf2N0QVkWFJ3K38h3Y3sikto2MxX7bBZf0
        jmCJCM7E6qQ02CvhoXcLiARiivkRX8JMfLxPc/9r3klmiPQIo0f0G2t6HpHszFMI
        DYLzIxivXltzGYkIRh9oywFr3h6tDDY3bkY0aAuSpd8IgjlOyd4trwXFvcuYSXnQ
        QrOAnhDvHKfuVbYCedP2akfYZYKy7iVhSps1tVxDP3j3Avx8nbQaZbcuSCh6SDLa
        fpzh41Svc0Nw/VaZU+WnHOepcUSyGa5NXXLblEkHu/gpLwQnlmcGtE5mLBd0QHBI
        /2FJ/vJdP8A+AB9r4tnUMswpYWXLjh6EDxBSsDAgxK3Yrd/EofhzOxt7TnQJfaSR
        8uxBgDZcVpj0/Sd1uKBw/3XX2vTv5RvY6XyvGGJlG84aT5jFtxcz7MLdd9NcqQzt
        gOQj+FCi6Lr2eISZ89hqblvuVcNVpSbIhgRIX41feohKlBNzsQKCAQEA6GOE5tzP
        Yp4GN2ktvDyKyQi/KuIwUK+9NmSF5Anq9U/HIvs4tz352a1Xs7wLW0cU2hGad85V
        7Wx5wQe8kkuL65Bn8RfyP83pdiEVbvb7bYbnxAbTXru1sXQ7RIsTqeZURfexkB8n
        qnxsbyF43cVxET8x+hvRXO6D6A9Fvo7jWn3EsoEwxOJtbwoX6M7v+Bi8pDCaLKX4
        ic/xFT1joir6RyBdBmMbEqEKByTL2iKi5oUounMQ1JJi5A9CdbJF53PpW42fAIxm
        GFRFp+dhMiaQSOBm6OJTcqHxZSFUs7wq+OAvIyIiPaEi553c/wsmExiEUrGklSWN
        /tzTLl5R+Wr7wwKCAQEA1+OAaVdPrQ5/k4sthPisLWcK44fdUT5DPhc7JbWgkL24
        /ps8uAeYNT0NIknoj6gtS9/3sG2h6gG02DLf1bE/1GtzWMfSjdY/imeZYEatup5a
        Xtb/FvPEoi+3LX6EboAjXw16DMmr9u8BPT430/4Iheots8Itwmt1GG8c5qkWZYaG
        ejDxcAcB1vM6jV6gPZwdqQ5l+8PKbFQhfCcHxFR4qy7Us8YWunveAZGFUMmv8lPg
        ePvca8+IdoPM7+JS9kQiQFOA3imLJ93VzpKganNifL9KekKZpdYCmplu4i6Ws1q/
        kg4mXURcenBYtOyeyJvpQdtO7VQ8jJH4HKXY2wZj7QKCAQAFpSU9Vm/TPXN5NRzf
        TbkxWP0L1aLG0v4NrDN0bqk+fEmiF+gwy1ieaQ+QVikQdpGTGopeDq0Xr2LlxYJX
        K26iskdUG/jOg/n/3J3grC8/Yd+Pa3sG+hhXzzMBXz+DCQ1TBclSbu9PvOYFbRK6
        kGlGufpE0Rgs4b5ijLxs/JuZPyTgETNWFQoDgINELIK3zCII+wVDwGRhNKPumCcr
        cU/TGn4oAZBOy4qq0cIB8oVyhBmRLepiv4uXbqd2pHX+QVqR1sbeBIsWXDW09nHt
        /fHTU2AsmBLe3gA3LLAaDaAdm5SJjfK2/IsUhUkxCNxL6nSMbbRJyze/0S1wGupy
        3J5xAoIBAQC4rTZl5niT83kSv9Yaj5bJ6AGajdi27OocrUa9hVdrOcCMnEMesfB0
        altX351/dj/5TgfV9pKxWPBYmXx8knmlvp0XbyggiQwl22WKxCtNHrTzuDrSaYjl
        rKen1Th4Rkj7wM2NLt9aBy4qM5USVZb451BdG1iFneK3GiXA8xfjlWZoFIIUcQoT
        1FFcKXwt9+Qvf8+hxOTeMkHKsKCmRBRNa2wstOEweVF6Sf+fEkjepP26wMjXuNpl
        d23SLusFG1epa0UrxqHxYoTJhwiOx1GSoRiW6W4CPMZRdbsy5OOpXZHO4SfUVOw/
        GOfpLRjPRwAMhAxKXOrG3P8/kmelRRwpAoIBAQCHaM15WyLzkAXSLwcf53ebSi3P
        A1jfv3ENN5AhJfil/wjEgynjZkXIrkHEdlapB9n/2eMTZswyX7JnB7nJyzQK75cm
        gi5h/+/Jt5vzExoXmXvw4Ku0bbbVHd6xXBw8ncjUC0ORnw0msS2zlJMi6YHpWJ2t
        8apJ1lLfZw+ELLBRoO4FeGDheerGQ6U/9EQhIluC2oFtfZBjZaKhjwrRswFIjXJj
        xNEw/2jkISK/DVL9oefH7ISMVwdYCCwCR0yqGTApmhTxJLk0iXdfE35mp3tTwP8/
        vY4jMo7bmTnH0NoLwIg90lQWYqh6kZcsax+Yt0M9I3sL9ML263qAITBgE2r4
        -----END RSA PRIVATE KEY-----
      AUTH_JWT_TOKEN_DURATION: 1h
      AUTH_JWT_TOKEN_REFRESH_DURATION: 1h
      DB_MYSQL_HOST: 127.0.0.1
      DB_MYSQL_PORT: 3306
      DB_MYSQL_NAME: ecommerce
      DB_MYSQL_USER: user
      DB_MYSQL_PASS: password
      DB_MYSQL_MAX_POOL_SIZE: 10
      DB.MYSQL.WITH_MIGRATION: true
      DB_MONGODB_HOST: 127.0.0.1
      DB_MONGODB_PORT: 27017
      DB_MONGODB_NAME: ecommerce
      DB_MONGODB_USER: ""
      DB_MONGODB_PASS: ""
      DB_MONGODB_MAX_POOL_SIZE: 10
    volumes:
      - ./.env:/app/.env 
      - ./migration:/app/migration
    networks:
      - localnetwork

networks:
  localnetwork: {}