// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.26.1
// source: proto/book.proto

package protogen

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BookServiceClient is the client API for BookService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BookServiceClient interface {
	CreateBook(ctx context.Context, in *RequestCreateBook, opts ...grpc.CallOption) (*Book, error)
	SearchBook(ctx context.Context, in *RequestSearchBook, opts ...grpc.CallOption) (*ResponseBook, error)
	AddCategory(ctx context.Context, in *RequestAddBookCategory, opts ...grpc.CallOption) (*ResponseAddBookCategory, error)
	Borrow(ctx context.Context, in *RequestBorrowingBook, opts ...grpc.CallOption) (*ResponseBorrowingBook, error)
	Return(ctx context.Context, in *RequestReturningBook, opts ...grpc.CallOption) (*ResponseReturningBook, error)
}

type bookServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBookServiceClient(cc grpc.ClientConnInterface) BookServiceClient {
	return &bookServiceClient{cc}
}

func (c *bookServiceClient) CreateBook(ctx context.Context, in *RequestCreateBook, opts ...grpc.CallOption) (*Book, error) {
	out := new(Book)
	err := c.cc.Invoke(ctx, "/syn.BookService/CreateBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookServiceClient) SearchBook(ctx context.Context, in *RequestSearchBook, opts ...grpc.CallOption) (*ResponseBook, error) {
	out := new(ResponseBook)
	err := c.cc.Invoke(ctx, "/syn.BookService/SearchBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookServiceClient) AddCategory(ctx context.Context, in *RequestAddBookCategory, opts ...grpc.CallOption) (*ResponseAddBookCategory, error) {
	out := new(ResponseAddBookCategory)
	err := c.cc.Invoke(ctx, "/syn.BookService/AddCategory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookServiceClient) Borrow(ctx context.Context, in *RequestBorrowingBook, opts ...grpc.CallOption) (*ResponseBorrowingBook, error) {
	out := new(ResponseBorrowingBook)
	err := c.cc.Invoke(ctx, "/syn.BookService/Borrow", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookServiceClient) Return(ctx context.Context, in *RequestReturningBook, opts ...grpc.CallOption) (*ResponseReturningBook, error) {
	out := new(ResponseReturningBook)
	err := c.cc.Invoke(ctx, "/syn.BookService/Return", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BookServiceServer is the server API for BookService service.
// All implementations must embed UnimplementedBookServiceServer
// for forward compatibility
type BookServiceServer interface {
	CreateBook(context.Context, *RequestCreateBook) (*Book, error)
	SearchBook(context.Context, *RequestSearchBook) (*ResponseBook, error)
	AddCategory(context.Context, *RequestAddBookCategory) (*ResponseAddBookCategory, error)
	Borrow(context.Context, *RequestBorrowingBook) (*ResponseBorrowingBook, error)
	Return(context.Context, *RequestReturningBook) (*ResponseReturningBook, error)
	mustEmbedUnimplementedBookServiceServer()
}

// UnimplementedBookServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBookServiceServer struct {
}

func (UnimplementedBookServiceServer) CreateBook(context.Context, *RequestCreateBook) (*Book, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBook not implemented")
}
func (UnimplementedBookServiceServer) SearchBook(context.Context, *RequestSearchBook) (*ResponseBook, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchBook not implemented")
}
func (UnimplementedBookServiceServer) AddCategory(context.Context, *RequestAddBookCategory) (*ResponseAddBookCategory, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddCategory not implemented")
}
func (UnimplementedBookServiceServer) Borrow(context.Context, *RequestBorrowingBook) (*ResponseBorrowingBook, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Borrow not implemented")
}
func (UnimplementedBookServiceServer) Return(context.Context, *RequestReturningBook) (*ResponseReturningBook, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Return not implemented")
}
func (UnimplementedBookServiceServer) mustEmbedUnimplementedBookServiceServer() {}

// UnsafeBookServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BookServiceServer will
// result in compilation errors.
type UnsafeBookServiceServer interface {
	mustEmbedUnimplementedBookServiceServer()
}

func RegisterBookServiceServer(s grpc.ServiceRegistrar, srv BookServiceServer) {
	s.RegisterService(&BookService_ServiceDesc, srv)
}

func _BookService_CreateBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestCreateBook)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServiceServer).CreateBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/syn.BookService/CreateBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServiceServer).CreateBook(ctx, req.(*RequestCreateBook))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookService_SearchBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestSearchBook)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServiceServer).SearchBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/syn.BookService/SearchBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServiceServer).SearchBook(ctx, req.(*RequestSearchBook))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookService_AddCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestAddBookCategory)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServiceServer).AddCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/syn.BookService/AddCategory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServiceServer).AddCategory(ctx, req.(*RequestAddBookCategory))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookService_Borrow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestBorrowingBook)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServiceServer).Borrow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/syn.BookService/Borrow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServiceServer).Borrow(ctx, req.(*RequestBorrowingBook))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookService_Return_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestReturningBook)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServiceServer).Return(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/syn.BookService/Return",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServiceServer).Return(ctx, req.(*RequestReturningBook))
	}
	return interceptor(ctx, in, info, handler)
}

// BookService_ServiceDesc is the grpc.ServiceDesc for BookService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BookService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "syn.BookService",
	HandlerType: (*BookServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBook",
			Handler:    _BookService_CreateBook_Handler,
		},
		{
			MethodName: "SearchBook",
			Handler:    _BookService_SearchBook_Handler,
		},
		{
			MethodName: "AddCategory",
			Handler:    _BookService_AddCategory_Handler,
		},
		{
			MethodName: "Borrow",
			Handler:    _BookService_Borrow_Handler,
		},
		{
			MethodName: "Return",
			Handler:    _BookService_Return_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/book.proto",
}
